---
- hosts: all
  gather_facts: yes

- hosts:
    - mail
  tasks:
    - name: Add vagrant hosts to /etc/hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        regexp='^(?:[0-9]{1,3}\.){3}[0-9]{1,3} {{item}}$'
        line="{{hostvars[item]}} {{hostvars[item]['ansible_default_ipv4']['address']}}"
      sudo: yes
      with_items: groups['all']
